---
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{resource_group}}"
      name: "{{virtual_network}}"
      address_prefixes: "{{vnet_address_prefix}}"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{resource_group}}"
      name: "{{subnet_name}}"
      address_prefix: "{{subnet_address_prefix}}"
      virtual_network: "{{virtual_network}}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{resource_group}}"
      allocation_method: "{{ip_allocation_method}}"
      name: "{{public_ip_name}}"
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{resource_group}}"
      name: "{{security_group_name}}" 
      rules:    
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: http
          protocol: Tcp
          destination_port_range: 7001
          access: Allow
          priority: 1002
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{resource_group}}"
      name: "{{NIC_name}}"      
      virtual_network: "{{virtual_network}}"
      subnet: "{{subnet_name}}"
      public_ip_name: "{{public_ip_name}}"
      security_group: "{{security_group_name}}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{resource_group}}"
      name: "{{vm_name}}"
      vm_size: "{{vm_size}}"
      admin_username: az2325
      storage_account: "{{storage_account}}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/az2325/.ssh/authorized_keys
          key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaic4FHbWoZXtKhXX6jkmW5f9wheLRyuGKF4p0NknfL99TaNqqB71P0haB7IMkAnh2tdR2H2JV4edQhb9nfdkjigGAS3P2+bVonbngODLYFmBOzIq67FSTmDeAp8MQX19ZimElTcPY1tFUlpZfQBehVX00wyIEvCeRl9x9g11fMvmePpvjPd83PZjrLcf4bOgvtHyZemuVuCfPG4JGpqt1cbaQg8ejHuCdzhEL8UbJ7Va2ahv0UM2NCQcfxbZqf5W5bE1mI/D7dw1rQj+1UPxpTzloKJoGFbOaR3zxFNMqp9/EwkJ9vdWE9jWJlQkrWQB8letaDb27rA2POe/HfxLF az2325@engspansiblerhel'
      network_interfaces: "{{NIC_name}}"
      image:
        offer: "{{offer_name}}"
        publisher: "{{publisher_name}}"
        sku: "{{sku}}"
        version: "{{version}}"
  - debug: msg="{{new_machine}}"

  - name: add host to the host file
    add_host:
     name: "{{new_machine}}"
     group: new_machine

  - name: ping the new machine
    ping:
     data: hello
    register: vm_op
  - debug: msg="{{vm_op}}"
