- name: add the new mysql server
  hosts: localhost
  connection: local
  roles:
     - role: ansible-role-mysql-master
       become: yes
       become_user: root

- name: Create database
  hosts: localhost
  connection: local
  tasks:
   - name: install database in mysql server
     mysql_db:
       name: mydb123
       state: present
       login_user: root
       login_password: root
