---
oracle_group: oinstall
oracle_user: oracle
ora_home: "/home/{{oracle_user}}/Weblogic"
MW_HOME: "{{ora_home}}/app/oracle/middleware"
oracle_group: oinstall
oracle_user: oracle
JDK_name: myJDK
jar_file_path: /home/az2325/fmw_12.2.1.3.0_wls_quick.jar
systemd_path: /etc/systemd/system
java_jdk: /home/az2325/myJava.rpm
