---
- debug: msg="{{MW_HOME}}"
- name: create a user and a  group for the universal installer
  shell: "{{item}}"
  with_items:    
      - groupadd -g 300 "{{oracle_group}}"
      - useradd -u 500 -g "{{oracle_group}}" "{{oracle_user}}"
  become: true
  become_user: root


- name: create the directories for the installation
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
  with_items:
     - "{{MW_HOME}}"
     - "{{ora_home}}/app/oracle/config/domains"
     - "{{ora_home}}/app/oracle/config/applications"
     - "{{ora_home}}/software"
     - "{{ora_home}}/software/Scripts"
     - "{{ora_home}}/app/oraInventory"
  become: true
  become_user: "{{oracle_user}}"


- name: change the ownership and the permissions of the directories
  shell: "{{item}}"
  with_items: 
      - chown -R "{{oracle_user}}":"{{oracle_group}}" "{{ora_home}}"
      - chmod -R 775 "{{ora_home}}"
  become: true
  become_user: "{{oracle_user}}"


- name: install the required version of java
  copy: 
     src : "{{java_jdk}}"
     dest: "{{ora_home}}/app/oracle/{{JDK_name}}.rpm"
     mode: 0777
- name: unpack the rpm file
  command: "rpm -Uvh {{JDK_name}}.rpm"
  args:
    chdir: "{{ora_home}}/app/oracle/"
  ignore_errors: true
- name: set the variable JAVA_HOME in the playbook context
  shell: readlink -f /usr/bin/java | sed "s:jre/bin/java::"
  register: JAVA_HOME
  become: true
  become_user: "{{oracle_user}}"

- debug: msg="{{JAVA_HOME}}"
  
#- name: Set the required environment variables
#  lineinfile: 
#        path: ~/.bash_profile
#        line: "{{item}}"
#        state: present
#  with_items:
#      - export JAVA_HOME=/home/oracle/Weblogic/app/oracle/jdk1.8.0_144
#      - export MW_HOME={{MW_HOME}}
#      - export WLS_HOME=$MW_HOME/wlserver
#      - export WL_HOME=$WLS_HOME
#      - export PATH=$JAVA_HOME/bin/java:$PATH
#  become: true
#  become_user: oracle
#- name: reload .bash_profile
#  shell: source ~/.bash_profile
#  become: true
#  become_user: oracle

- name: Copy the jar file to the software folder
  copy: 
    src: "{{jar_file_path}}"
    dest: "{{ora_home}}/software"
    mode: 0755  
  become: true
  become_user: "{{oracle_user}}"
- name: setup files for silent install
  template: src="{{item.file}}.j2" dest="{{item.dest}}/{{item.file}}"
  with_items:
     - { file: "oraInst.loc", dest: "{{ora_home}}/software"}
     - { file: "wls.rsp", dest: "{{ora_home}}/software"}
     - { file: "domain.xml", dest: "{{ora_home}}/software/Scripts"}
     - { file: "wls_nodemanager.service", dest: "{{systemd_path}}"}
     - { file: "wls_adminmanager.service", dest: "{{systemd_path}}"}
  become: true
  become_user: root

- name: Run the installer (jar_file)
  command: "{{JAVA_HOME.stdout}}/bin/java -Xmx1024m -jar {{ora_home}}/software/fmw_12.2.1.3.0_wls_quick.jar -silent -responseFile {{ora_home}}/software/wls.rsp -invPtrLoc {{ora_home}}/software/oraInst.loc ORACLE_HOME={{MW_HOME}}"
  become: true
  become_user: "{{oracle_user}}"
  register: wl_install

 
- name: View the output of install
  debug: msg="{{wl_install.stdout}}"

- name: Silent install the Domain 
  command: sh wlst.sh "{{ora_home}}/software/Scripts/domain.xml"
  args:
    chdir: "{{MW_HOME}}/wlserver/common/bin"
  register: op1
  become: true
  become_user: "{{oracle_user}}"
- debug: msg="{{op1}}"

- name: start the weblogic as a service
  shell: |
      systemctl start wls_nodemanager.service
      systemctl start wls_adminmanager.service
  
- name: deploy the war file
  copy:
   src: ~/sample.war
   dest: "{{MW_HOME}}/user_projects/domains/myFirstDomain/autodeploy"
   mode: 0755
  become: true
  become_user: "{{oracle_user}}"
